version: '3.4'


services:

  opensearch:
    image: opensearchproject/opensearch:1.2.0
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch/config/decompound_word_list.nl.txt:/usr/share/opensearch/config/decompound_word_list.nl.txt
    ports:
      - "127.0.0.1:9200:9200"

volumes:
  opensearch-data:
