from search_client.factories.learning_material import generate_nl_material
from search_client.factories.research_product import generate_nl_product
from search_client.factories.projects import generate_project
