from search_client.serializers.products import LearningMaterial, ResearchProduct
from search_client.serializers.projects import Project
from search_client.serializers.organizations import Organization
